-- MySQL Script generated by MySQL Workbench
-- Mon Sep 15 16:36:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema merkadit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema merkadit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `merkadit` DEFAULT CHARACTER SET utf8mb3 ;
USE `merkadit` ;

-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Countries` (
  `countryID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`countryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_States` (
  `stateID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `countryID` TINYINT NOT NULL,
  PRIMARY KEY (`stateID`),
  INDEX `fk_States_Countries_idx` (`countryID` ASC) VISIBLE,
  CONSTRAINT `fk_States_Countries`
    FOREIGN KEY (`countryID`)
    REFERENCES `merkadit`.`mkd_Countries` (`countryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Cities` (
  `cityID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `stateID` INT NOT NULL,
  PRIMARY KEY (`cityID`),
  INDEX `fk_Cities_States_idx` (`stateID` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States`
    FOREIGN KEY (`stateID`)
    REFERENCES `merkadit`.`mkd_States` (`stateID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Addresses` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(200) NOT NULL,
  `line2` VARCHAR(200) NULL DEFAULT NULL,
  `zipCode` VARCHAR(10) NULL DEFAULT NULL,
  `location` POINT NULL DEFAULT NULL,
  `cityID` INT NOT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_Addresses_Cities_idx` (`cityID` ASC) VISIBLE,
  CONSTRAINT `fk_Addresses_Cities`
    FOREIGN KEY (`cityID`)
    REFERENCES `merkadit`.`mkd_Cities` (`cityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `passwordHash` VARBINARY(250) NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastLogin` DATETIME NULL DEFAULT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_AddressXUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_AddressXUsers` (
  `addressXUserID` INT NOT NULL AUTO_INCREMENT,
  `addressID` INT NOT NULL,
  `userID` INT NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `isDefault` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`addressXUserID`),
  INDEX `fk_AddressXUsers_Addresses_idx` (`addressID` ASC) VISIBLE,
  INDEX `fk_AddressXUsers_Users_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_AddressXUsers_Addresses`
    FOREIGN KEY (`addressID`)
    REFERENCES `merkadit`.`mkd_Addresses` (`addressID`),
  CONSTRAINT `fk_AddressXUsers_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Buildings` (
  `buildingID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `totalArea` DECIMAL(10,2) NULL DEFAULT NULL,
  `floors` TINYINT NULL DEFAULT NULL,
  `openingTime` TIME NULL DEFAULT NULL,
  `closingTime` TIME NULL DEFAULT NULL,
  `adminUserID` INT NOT NULL,
  `addressID` INT NOT NULL,
  `initialInvestment` DECIMAL(15,2) NULL DEFAULT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`buildingID`),
  INDEX `fk_Buildings_Users_idx` (`adminUserID` ASC) VISIBLE,
  INDEX `fk_Buildings_Addresses_idx` (`addressID` ASC) VISIBLE,
  CONSTRAINT `fk_Buildings_Addresses`
    FOREIGN KEY (`addressID`)
    REFERENCES `merkadit`.`mkd_Addresses` (`addressID`),
  CONSTRAINT `fk_Buildings_Users`
    FOREIGN KEY (`adminUserID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ProductCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ProductCategories` (
  `productCategoryID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`productCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_CommerceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_CommerceTypes` (
  `commerceTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`commerceTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Commerces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Commerces` (
  `commerceID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `legalName` VARCHAR(200) NULL DEFAULT NULL,
  `taxID` VARCHAR(30) NULL DEFAULT NULL,
  `commerceTypeID` TINYINT NOT NULL,
  `ownerUserID` INT NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (`commerceID`),
  UNIQUE INDEX `taxID_UNIQUE` (`taxID` ASC) VISIBLE,
  INDEX `fk_Commerces_CommerceTypes_idx` (`commerceTypeID` ASC) VISIBLE,
  INDEX `fk_Commerces_Users_idx` (`ownerUserID` ASC) VISIBLE,
  CONSTRAINT `fk_Commerces_CommerceTypes`
    FOREIGN KEY (`commerceTypeID`)
    REFERENCES `merkadit`.`mkd_CommerceTypes` (`commerceTypeID`),
  CONSTRAINT `fk_Commerces_Users`
    FOREIGN KEY (`ownerUserID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ContactTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ContactTypes` (
  `contactTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`contactTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_CommerceContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_CommerceContacts` (
  `commerceXContactID` INT NOT NULL AUTO_INCREMENT,
  `commerceID` INT NOT NULL,
  `contactTypeID` TINYINT NOT NULL,
  `value` VARCHAR(80) NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`commerceXContactID`),
  INDEX `fk_CommerceContacts_Commerces_idx` (`commerceID` ASC) VISIBLE,
  INDEX `fk_CommerceContacts_ContactTypes_idx` (`contactTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_CommerceContacts_Commerces`
    FOREIGN KEY (`commerceID`)
    REFERENCES `merkadit`.`mkd_Commerces` (`commerceID`),
  CONSTRAINT `fk_CommerceContacts_ContactTypes`
    FOREIGN KEY (`contactTypeID`)
    REFERENCES `merkadit`.`mkd_ContactTypes` (`contactTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Currencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Currencies` (
  `currencyID` SMALLINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `isoCode` VARCHAR(3) NOT NULL,
  `currencySymbol` VARCHAR(5) NULL DEFAULT NULL,
  `countryID` TINYINT NOT NULL,
  PRIMARY KEY (`currencyID`),
  INDEX `fk_Currencies_Countries_idx` (`countryID` ASC) VISIBLE,
  CONSTRAINT `fk_Currencies_Countries`
    FOREIGN KEY (`countryID`)
    REFERENCES `merkadit`.`mkd_Countries` (`countryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_CommerceReports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_CommerceReports` (
  `commerceReportID` INT NOT NULL AUTO_INCREMENT,
  `commerceID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `totalSales` DECIMAL(16,2) NOT NULL,
  `totalCosts` DECIMAL(16,2) NOT NULL,
  `grossProfit` DECIMAL(16,2) NOT NULL,
  `totalRent` DECIMAL(16,2) NOT NULL,
  `commissionPaid` DECIMAL(16,2) NOT NULL,
  `netProfit` DECIMAL(16,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userID` INT NOT NULL,
  PRIMARY KEY (`commerceReportID`),
  INDEX `fk_CommerceReports_Commerces_idx` (`commerceID` ASC) VISIBLE,
  INDEX `fk_CommerceReports_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_CommerceReports_Users_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_CommerceReports_Commerces`
    FOREIGN KEY (`commerceID`)
    REFERENCES `merkadit`.`mkd_Commerces` (`commerceID`),
  CONSTRAINT `fk_CommerceReports_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_CommerceReports_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ContractStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ContractStatus` (
  `contractStatusID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`contractStatusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ScheduleRecurrencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ScheduleRecurrencies` (
  `scheduleRecurrencyID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `intervalDays` INT NOT NULL,
  PRIMARY KEY (`scheduleRecurrencyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Schedules` (
  `scheduleID` INT NOT NULL AUTO_INCREMENT,
  `scheduleRecurrencyID` TINYINT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `lastExecute` DATETIME NULL DEFAULT NULL,
  `nextExecute` DATETIME NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`scheduleID`),
  INDEX `fk_Schedules_ScheduleRecurrencies_idx` (`scheduleRecurrencyID` ASC) VISIBLE,
  CONSTRAINT `fk_Schedules_ScheduleRecurrencies`
    FOREIGN KEY (`scheduleRecurrencyID`)
    REFERENCES `merkadit`.`mkd_ScheduleRecurrencies` (`scheduleRecurrencyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Floors` (
  `floorID` INT NOT NULL AUTO_INCREMENT,
  `buildingID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `floorNumber` TINYINT NOT NULL,
  PRIMARY KEY (`floorID`),
  INDEX `fk_Floors_Buildings_idx` (`buildingID` ASC) VISIBLE,
  CONSTRAINT `fk_Floors_Buildings`
    FOREIGN KEY (`buildingID`)
    REFERENCES `merkadit`.`mkd_Buildings` (`buildingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_SpaceStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_SpaceStatus` (
  `statusID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_SpaceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_SpaceTypes` (
  `spaceTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`spaceTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Spaces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Spaces` (
  `spaceID` INT NOT NULL AUTO_INCREMENT,
  `floorID` INT NOT NULL,
  `spaceCode` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `area` DECIMAL(10,2) NULL DEFAULT NULL,
  `spaceTypeID` TINYINT NOT NULL,
  `spaceStatusID` TINYINT NOT NULL,
  `baseRent` DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (`spaceID`),
  INDEX `fk_Spaces_Floors_idx` (`floorID` ASC) VISIBLE,
  INDEX `fk_Spaces_SpaceTypes_idx` (`spaceTypeID` ASC) VISIBLE,
  INDEX `fk_Spaces_SpaceStatus_idx` (`spaceStatusID` ASC) VISIBLE,
  CONSTRAINT `fk_Spaces_Floors`
    FOREIGN KEY (`floorID`)
    REFERENCES `merkadit`.`mkd_Floors` (`floorID`),
  CONSTRAINT `fk_Spaces_SpaceStatus`
    FOREIGN KEY (`spaceStatusID`)
    REFERENCES `merkadit`.`mkd_SpaceStatus` (`statusID`),
  CONSTRAINT `fk_Spaces_SpaceTypes`
    FOREIGN KEY (`spaceTypeID`)
    REFERENCES `merkadit`.`mkd_SpaceTypes` (`spaceTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Contracts` (
  `contractID` INT NOT NULL AUTO_INCREMENT,
  `contractNumber` VARCHAR(50) NOT NULL,
  `commerceID` INT NOT NULL,
  `spaceID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `documentUrl` VARCHAR(500) NULL DEFAULT NULL,
  `baseRent` DECIMAL(16,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `commissionPercentage` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `scheduleID` INT NULL DEFAULT NULL,
  `contractStatusID` TINYINT NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NOT NULL,
  PRIMARY KEY (`contractID`),
  UNIQUE INDEX `contractNumber_UNIQUE` (`contractNumber` ASC) VISIBLE,
  INDEX `fk_Contracts_Commerces_idx` (`commerceID` ASC) VISIBLE,
  INDEX `fk_Contracts_Spaces_idx` (`spaceID` ASC) VISIBLE,
  INDEX `fk_Contracts_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_Contracts_Schedules_idx` (`scheduleID` ASC) VISIBLE,
  INDEX `fk_Contracts_ContractStatus_idx` (`contractStatusID` ASC) VISIBLE,
  INDEX `fk_Contracts_Users_idx` (`createdBy` ASC) VISIBLE,
  CONSTRAINT `fk_Contracts_Commerces`
    FOREIGN KEY (`commerceID`)
    REFERENCES `merkadit`.`mkd_Commerces` (`commerceID`),
  CONSTRAINT `fk_Contracts_ContractStatus`
    FOREIGN KEY (`contractStatusID`)
    REFERENCES `merkadit`.`mkd_ContractStatus` (`contractStatusID`),
  CONSTRAINT `fk_Contracts_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_Contracts_Schedules`
    FOREIGN KEY (`scheduleID`)
    REFERENCES `merkadit`.`mkd_Schedules` (`scheduleID`),
  CONSTRAINT `fk_Contracts_Spaces`
    FOREIGN KEY (`spaceID`)
    REFERENCES `merkadit`.`mkd_Spaces` (`spaceID`),
  CONSTRAINT `fk_Contracts_Users`
    FOREIGN KEY (`createdBy`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_CommerceReportDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_CommerceReportDetails` (
  `commerceReportDetailID` INT NOT NULL AUTO_INCREMENT,
  `commerceReportID` INT NOT NULL,
  `contractID` INT NOT NULL,
  `salesAmount` DECIMAL(16,2) NOT NULL,
  `rentAmount` DECIMAL(16,2) NOT NULL,
  `commissionAmount` DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (`commerceReportDetailID`),
  INDEX `fk_CommerceReportDetails_CommerceReports_idx` (`commerceReportID` ASC) VISIBLE,
  INDEX `fk_CommerceReportDetails_Contracts_idx` (`contractID` ASC) VISIBLE,
  CONSTRAINT `fk_CommerceReportDetails_CommerceReports`
    FOREIGN KEY (`commerceReportID`)
    REFERENCES `merkadit`.`mkd_CommerceReports` (`commerceReportID`),
  CONSTRAINT `fk_CommerceReportDetails_Contracts`
    FOREIGN KEY (`contractID`)
    REFERENCES `merkadit`.`mkd_Contracts` (`contractID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_CustomerTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_CustomerTypes` (
  `customerTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`customerTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `customerTypeID` TINYINT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `taxID` VARCHAR(30) NULL DEFAULT NULL,
  `birthdate` DATETIME NULL DEFAULT NULL,
  `addressID` INT NULL DEFAULT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`customerID`),
  INDEX `fk_Customers_CustomerTypes_idx` (`customerTypeID` ASC) VISIBLE,
  INDEX `fk_Customers_Addresses_idx` (`addressID` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Addresses`
    FOREIGN KEY (`addressID`)
    REFERENCES `merkadit`.`mkd_Addresses` (`addressID`),
  CONSTRAINT `fk_Customers_CustomerTypes`
    FOREIGN KEY (`customerTypeID`)
    REFERENCES `merkadit`.`mkd_CustomerTypes` (`customerTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ExchangeRates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ExchangeRates` (
  `exchangeRateID` SMALLINT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL DEFAULT NULL,
  `exchangeRate` DECIMAL(10,4) NOT NULL,
  `currencySourceID` SMALLINT NOT NULL,
  `currencyDestinyID` SMALLINT NOT NULL,
  `current` BIT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`exchangeRateID`),
  INDEX `fk_ExchangeRates_CurrencySource_idx` (`currencySourceID` ASC) VISIBLE,
  INDEX `fk_ExchangeRates_CurrencyDestiny_idx` (`currencyDestinyID` ASC) VISIBLE,
  CONSTRAINT `fk_ExchangeRates_CurrencyDestiny`
    FOREIGN KEY (`currencyDestinyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_ExchangeRates_CurrencySource`
    FOREIGN KEY (`currencySourceID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ExpenseTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ExpenseTypes` (
  `expenseTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`expenseTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Expenses` (
  `expenseID` INT NOT NULL AUTO_INCREMENT,
  `buildingID` INT NULL DEFAULT NULL,
  `spaceID` INT NULL DEFAULT NULL,
  `description` VARCHAR(500) NOT NULL,
  `amount` DECIMAL(16,2) NOT NULL,
  `expenseDate` DATE NOT NULL,
  `expenseTypeID` TINYINT NOT NULL,
  `invoiceNumber` VARCHAR(50) NULL DEFAULT NULL,
  `supplierName` VARCHAR(100) NULL DEFAULT NULL,
  `createdBy` INT NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`expenseID`),
  INDEX `fk_Expenses_Buildings_idx` (`buildingID` ASC) VISIBLE,
  INDEX `fk_Expenses_Spaces_idx` (`spaceID` ASC) VISIBLE,
  INDEX `fk_Expenses_ExpenseTypes_idx` (`expenseTypeID` ASC) VISIBLE,
  INDEX `fk_Expenses_Users_idx` (`createdBy` ASC) VISIBLE,
  CONSTRAINT `fk_Expenses_Buildings`
    FOREIGN KEY (`buildingID`)
    REFERENCES `merkadit`.`mkd_Buildings` (`buildingID`),
  CONSTRAINT `fk_Expenses_ExpenseTypes`
    FOREIGN KEY (`expenseTypeID`)
    REFERENCES `merkadit`.`mkd_ExpenseTypes` (`expenseTypeID`),
  CONSTRAINT `fk_Expenses_Spaces`
    FOREIGN KEY (`spaceID`)
    REFERENCES `merkadit`.`mkd_Spaces` (`spaceID`),
  CONSTRAINT `fk_Expenses_Users`
    FOREIGN KEY (`createdBy`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_ReportTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_ReportTypes` (
  `reportTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`reportTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_FinancialReports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_FinancialReports` (
  `reportID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `totalRevenue` DECIMAL(16,2) NOT NULL,
  `totalExpenses` DECIMAL(16,2) NOT NULL,
  `netIncome` DECIMAL(16,2) NOT NULL,
  `grossMargin` DECIMAL(5,2) NULL DEFAULT NULL,
  `occupancyRate` DECIMAL(5,2) NULL DEFAULT NULL,
  `currencyID` SMALLINT NOT NULL,
  `reportTypeID` TINYINT NOT NULL,
  `documentURL` VARCHAR(250) NULL DEFAULT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reportID`),
  INDEX `fk_FinancialReports_Users_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_FinancialReports_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_FinancialReports_ReportTypes_idx` (`reportTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_FinancialReports_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_FinancialReports_ReportTypes`
    FOREIGN KEY (`reportTypeID`)
    REFERENCES `merkadit`.`mkd_ReportTypes` (`reportTypeID`),
  CONSTRAINT `fk_FinancialReports_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_InvestmentCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_InvestmentCategories` (
  `investmentCategoryID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `isCapital` BIT(1) NOT NULL DEFAULT b'0',
  `depreciationMonths` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`investmentCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Investments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Investments` (
  `investmentID` INT NOT NULL AUTO_INCREMENT,
  `spaceID` INT NULL DEFAULT NULL,
  `contractID` INT NULL DEFAULT NULL,
  `description` VARCHAR(500) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `investmentDate` DATE NOT NULL,
  `investmentCategoryID` TINYINT NOT NULL,
  `userID` INT NOT NULL,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`investmentID`),
  INDEX `fk_Investments_Spaces_idx` (`spaceID` ASC) VISIBLE,
  INDEX `fk_Investments_Contracts_idx` (`contractID` ASC) VISIBLE,
  INDEX `fk_Investments_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_Investments_InvestmentCategories_idx` (`investmentCategoryID` ASC) VISIBLE,
  INDEX `fk_Investments_Users_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_Investments_Contracts`
    FOREIGN KEY (`contractID`)
    REFERENCES `merkadit`.`mkd_Contracts` (`contractID`),
  CONSTRAINT `fk_Investments_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_Investments_InvestmentCategories`
    FOREIGN KEY (`investmentCategoryID`)
    REFERENCES `merkadit`.`mkd_InvestmentCategories` (`investmentCategoryID`),
  CONSTRAINT `fk_Investments_Spaces`
    FOREIGN KEY (`spaceID`)
    REFERENCES `merkadit`.`mkd_Spaces` (`spaceID`),
  CONSTRAINT `fk_Investments_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_FinancialReportDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_FinancialReportDetails` (
  `financialReportDetailID` INT NOT NULL AUTO_INCREMENT,
  `financialReportID` INT NOT NULL,
  `expensesID` INT NULL DEFAULT NULL,
  `investmentID` INT NULL DEFAULT NULL,
  `commerceReportID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`financialReportDetailID`),
  INDEX `fk_FinancialReportDetails_FinancialReports_idx` (`financialReportID` ASC) VISIBLE,
  INDEX `fk_FinancialReportDetails_Expenses_idx` (`expensesID` ASC) VISIBLE,
  INDEX `fk_FinancialReportDetails_Investments_idx` (`investmentID` ASC) VISIBLE,
  INDEX `fk_FinancialReportDetails_CommerceReports_idx` (`commerceReportID` ASC) VISIBLE,
  CONSTRAINT `fk_FinancialReportDetails_CommerceReports`
    FOREIGN KEY (`commerceReportID`)
    REFERENCES `merkadit`.`mkd_CommerceReports` (`commerceReportID`),
  CONSTRAINT `fk_FinancialReportDetails_Expenses`
    FOREIGN KEY (`expensesID`)
    REFERENCES `merkadit`.`mkd_Expenses` (`expenseID`),
  CONSTRAINT `fk_FinancialReportDetails_FinancialReports`
    FOREIGN KEY (`financialReportID`)
    REFERENCES `merkadit`.`mkd_FinancialReports` (`reportID`),
  CONSTRAINT `fk_FinancialReportDetails_Investments`
    FOREIGN KEY (`investmentID`)
    REFERENCES `merkadit`.`mkd_Investments` (`investmentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_MovementTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_MovementTypes` (
  `movementTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`movementTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Products` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `commerceID` INT NOT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `barcode` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `productCategoryID` INT NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `stockQuantity` INT NOT NULL DEFAULT '0',
  `minStock` INT NULL DEFAULT '0',
  `maxStock` INT NULL DEFAULT NULL,
  `isActive` BIT(1) NOT NULL DEFAULT b'1',
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`productID`),
  INDEX `fk_Products_Commerces_idx` (`commerceID` ASC) VISIBLE,
  INDEX `fk_Products_Categories_idx` (`productCategoryID` ASC) VISIBLE,
  INDEX `fk_Products_Currencies_idx` (`currencyID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories`
    FOREIGN KEY (`productCategoryID`)
    REFERENCES `merkadit`.`mkd_ProductCategories` (`productCategoryID`),
  CONSTRAINT `fk_Products_Commerces`
    FOREIGN KEY (`commerceID`)
    REFERENCES `merkadit`.`mkd_Commerces` (`commerceID`),
  CONSTRAINT `fk_Products_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_InventoryMovements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_InventoryMovements` (
  `movementID` INT NOT NULL AUTO_INCREMENT,
  `productID` INT NOT NULL,
  `movementTypeID` TINYINT NOT NULL,
  `stockQuantity` INT NOT NULL,
  `referenceDescription` VARCHAR(100) NULL DEFAULT NULL,
  `referenceID` INT NULL DEFAULT NULL,
  `movementDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(50) NOT NULL,
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`movementID`),
  INDEX `fk_InventoryMovements_Products_idx` (`productID` ASC) VISIBLE,
  INDEX `fk_InventoryMovements_MovementTypes_idx` (`movementTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_InventoryMovements_MovementTypes`
    FOREIGN KEY (`movementTypeID`)
    REFERENCES `merkadit`.`mkd_MovementTypes` (`movementTypeID`),
  CONSTRAINT `fk_InventoryMovements_Products`
    FOREIGN KEY (`productID`)
    REFERENCES `merkadit`.`mkd_Products` (`productID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_LogLevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_LogLevels` (
  `logLevelID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`logLevelID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_LogSources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_LogSources` (
  `logSourceID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`logSourceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_LogTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_LogTypes` (
  `logTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`logTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Logs` (
  `logID` BIGINT NOT NULL AUTO_INCREMENT,
  `posttime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(500) NOT NULL,
  `computer` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `ref1ID` BIGINT NULL DEFAULT NULL,
  `ref2ID` BIGINT NULL DEFAULT NULL,
  `value1` VARCHAR(200) NULL DEFAULT NULL,
  `value2` VARCHAR(200) NULL DEFAULT NULL,
  `logTypeID` TINYINT NOT NULL,
  `logLevelID` TINYINT NOT NULL,
  `logSourceID` TINYINT NOT NULL,
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`logID`),
  INDEX `fk_Logs_LogTypes_idx` (`logTypeID` ASC) VISIBLE,
  INDEX `fk_Logs_LogLevels_idx` (`logLevelID` ASC) VISIBLE,
  INDEX `fk_Logs_LogSources_idx` (`logSourceID` ASC) VISIBLE,
  CONSTRAINT `fk_Logs_LogLevels`
    FOREIGN KEY (`logLevelID`)
    REFERENCES `merkadit`.`mkd_LogLevels` (`logLevelID`),
  CONSTRAINT `fk_Logs_LogSources`
    FOREIGN KEY (`logSourceID`)
    REFERENCES `merkadit`.`mkd_LogSources` (`logSourceID`),
  CONSTRAINT `fk_Logs_LogTypes`
    FOREIGN KEY (`logTypeID`)
    REFERENCES `merkadit`.`mkd_LogTypes` (`logTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_PaymentMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_PaymentMethods` (
  `paymentMethodID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` VARCHAR(20) NOT NULL,
  `requiresReference` BIT(1) NOT NULL DEFAULT b'0',
  `processingFee` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`paymentMethodID`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_PaymentStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_PaymentStatus` (
  `paymentStatusID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`paymentStatusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_PaymentTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_PaymentTypes` (
  `paymentTypeID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`paymentTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Payment` (
  `paymentID` INT NOT NULL AUTO_INCREMENT,
  `paymentMethodID` TINYINT NOT NULL,
  `paymentTypeID` TINYINT NOT NULL,
  `transactionAmount` DECIMAL(16,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `paymentDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paymentReference` VARCHAR(100) NULL DEFAULT NULL,
  `paymentConfirmation` VARCHAR(100) NULL DEFAULT NULL,
  `paymentStatusID` TINYINT NOT NULL,
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`paymentID`),
  INDEX `fk_Payment_PaymentMethods_idx` (`paymentMethodID` ASC) VISIBLE,
  INDEX `fk_Payment_PaymentTypes_idx` (`paymentTypeID` ASC) VISIBLE,
  INDEX `fk_Payment_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_Payment_PaymentStatus_idx` (`paymentStatusID` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_Payment_PaymentMethods`
    FOREIGN KEY (`paymentMethodID`)
    REFERENCES `merkadit`.`mkd_PaymentMethods` (`paymentMethodID`),
  CONSTRAINT `fk_Payment_PaymentStatus`
    FOREIGN KEY (`paymentStatusID`)
    REFERENCES `merkadit`.`mkd_PaymentStatus` (`paymentStatusID`),
  CONSTRAINT `fk_Payment_PaymentTypes`
    FOREIGN KEY (`paymentTypeID`)
    REFERENCES `merkadit`.`mkd_PaymentTypes` (`paymentTypeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Permissions` (
  `permissionID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `code` VARCHAR(20) NOT NULL,
  `module` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`permissionID`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Roles` (
  `roleID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_PermissionXRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_PermissionXRoles` (
  `permissionID` INT NOT NULL,
  `roleID` INT NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`permissionID`, `roleID`),
  INDEX `fk_PermissionXRoles_Roles_idx` (`roleID` ASC) VISIBLE,
  CONSTRAINT `fk_PermissionXRoles_Permissions`
    FOREIGN KEY (`permissionID`)
    REFERENCES `merkadit`.`mkd_Permissions` (`permissionID`),
  CONSTRAINT `fk_PermissionXRoles_Roles`
    FOREIGN KEY (`roleID`)
    REFERENCES `merkadit`.`mkd_Roles` (`roleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_PriceHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_PriceHistory` (
  `priceHistoryID` INT NOT NULL AUTO_INCREMENT,
  `productID` INT NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `cost` DECIMAL(15,2) NULL DEFAULT NULL,
  `currencyID` SMALLINT NOT NULL,
  `isCurrent` BIT(1) NOT NULL DEFAULT b'1',
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`priceHistoryID`),
  INDEX `fk_PriceHistory_Products_idx` (`productID` ASC) VISIBLE,
  INDEX `fk_PriceHistory_Currencies_idx` (`currencyID` ASC) VISIBLE,
  CONSTRAINT `fk_PriceHistory_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_PriceHistory_Products`
    FOREIGN KEY (`productID`)
    REFERENCES `merkadit`.`mkd_Products` (`productID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_SaleStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_SaleStatus` (
  `saleStatusID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`saleStatusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Sales` (
  `saleID` INT NOT NULL AUTO_INCREMENT,
  `commerceID` INT NOT NULL,
  `invoiceNumber` VARCHAR(50) NOT NULL,
  `saleDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customerID` INT NULL DEFAULT NULL,
  `subtotal` DECIMAL(16,2) NOT NULL,
  `discountAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `taxAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `totalAmount` DECIMAL(16,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `computer` VARCHAR(50) NULL DEFAULT NULL,
  `userID` INT NOT NULL,
  `paymentMethodID` TINYINT NOT NULL,
  `paymentReference` VARCHAR(100) NULL DEFAULT NULL,
  `paymentConfirmation` VARCHAR(100) NULL DEFAULT NULL,
  `saleStatusID` TINYINT NOT NULL,
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`saleID`),
  INDEX `fk_Sales_Commerces_idx` (`commerceID` ASC) VISIBLE,
  INDEX `fk_Sales_Customers_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_Sales_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_Sales_Users_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_Sales_PaymentMethods_idx` (`paymentMethodID` ASC) VISIBLE,
  INDEX `fk_Sales_SaleStatus_idx` (`saleStatusID` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Commerces`
    FOREIGN KEY (`commerceID`)
    REFERENCES `merkadit`.`mkd_Commerces` (`commerceID`),
  CONSTRAINT `fk_Sales_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_Sales_Customers`
    FOREIGN KEY (`customerID`)
    REFERENCES `merkadit`.`mkd_Customers` (`customerID`),
  CONSTRAINT `fk_Sales_PaymentMethods`
    FOREIGN KEY (`paymentMethodID`)
    REFERENCES `merkadit`.`mkd_PaymentMethods` (`paymentMethodID`),
  CONSTRAINT `fk_Sales_SaleStatus`
    FOREIGN KEY (`saleStatusID`)
    REFERENCES `merkadit`.`mkd_SaleStatus` (`saleStatusID`),
  CONSTRAINT `fk_Sales_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_SaleDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_SaleDetails` (
  `saleDetailID` INT NOT NULL AUTO_INCREMENT,
  `saleID` INT NOT NULL,
  `productID` INT NOT NULL,
  `unitPrice` DECIMAL(16,2) NOT NULL,
  `quantity` INT NOT NULL,
  `discountAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `subtotal` DECIMAL(16,2) NOT NULL,
  PRIMARY KEY (`saleDetailID`),
  INDEX `fk_SaleDetails_Sales_idx` (`saleID` ASC) VISIBLE,
  INDEX `fk_SaleDetails_Products_idx` (`productID` ASC) VISIBLE,
  CONSTRAINT `fk_SaleDetails_Products`
    FOREIGN KEY (`productID`)
    REFERENCES `merkadit`.`mkd_Products` (`productID`),
  CONSTRAINT `fk_SaleDetails_Sales`
    FOREIGN KEY (`saleID`)
    REFERENCES `merkadit`.`mkd_Sales` (`saleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_SettlementStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_SettlementStatus` (
  `settlementStatusID` TINYINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`settlementStatusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_Settlements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_Settlements` (
  `settlementID` INT NOT NULL AUTO_INCREMENT,
  `contractID` INT NOT NULL,
  `scheduleID` INT NULL DEFAULT NULL,
  `baseRentAmount` DECIMAL(16,2) NOT NULL,
  `totalSales` DECIMAL(16,2) NOT NULL,
  `commissionAmount` DECIMAL(16,2) NOT NULL,
  `totalAmount` DECIMAL(16,2) NOT NULL,
  `currencyID` SMALLINT NOT NULL,
  `settlementDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `settlementStatusID` TINYINT NOT NULL,
  `paidDate` DATETIME NULL DEFAULT NULL,
  `createdBy` INT NOT NULL,
  PRIMARY KEY (`settlementID`),
  INDEX `fk_Settlements_Contracts_idx` (`contractID` ASC) VISIBLE,
  INDEX `fk_Settlements_Schedules_idx` (`scheduleID` ASC) VISIBLE,
  INDEX `fk_Settlements_Currencies_idx` (`currencyID` ASC) VISIBLE,
  INDEX `fk_Settlements_SettlementStatus_idx` (`settlementStatusID` ASC) VISIBLE,
  INDEX `fk_Settlements_Users_idx` (`createdBy` ASC) VISIBLE,
  CONSTRAINT `fk_Settlements_Contracts`
    FOREIGN KEY (`contractID`)
    REFERENCES `merkadit`.`mkd_Contracts` (`contractID`),
  CONSTRAINT `fk_Settlements_Currencies`
    FOREIGN KEY (`currencyID`)
    REFERENCES `merkadit`.`mkd_Currencies` (`currencyID`),
  CONSTRAINT `fk_Settlements_Schedules`
    FOREIGN KEY (`scheduleID`)
    REFERENCES `merkadit`.`mkd_Schedules` (`scheduleID`),
  CONSTRAINT `fk_Settlements_SettlementStatus`
    FOREIGN KEY (`settlementStatusID`)
    REFERENCES `merkadit`.`mkd_SettlementStatus` (`settlementStatusID`),
  CONSTRAINT `fk_Settlements_Users`
    FOREIGN KEY (`createdBy`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_UserContacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_UserContacts` (
  `contactID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `contactTypeID` TINYINT NOT NULL,
  `value` VARCHAR(80) NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `deleted` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`contactID`),
  INDEX `fk_UserContacts_Users_idx` (`userID` ASC) VISIBLE,
  INDEX `fk_UserContacts_ContactTypes_idx` (`contactTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_UserContacts_ContactTypes`
    FOREIGN KEY (`contactTypeID`)
    REFERENCES `merkadit`.`mkd_ContactTypes` (`contactTypeID`),
  CONSTRAINT `fk_UserContacts_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `merkadit`.`mkd_UserXRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `merkadit`.`mkd_UserXRoles` (
  `userID` INT NOT NULL,
  `roleID` INT NOT NULL,
  `postTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `checksum` VARBINARY(250) NULL DEFAULT NULL,
  PRIMARY KEY (`userID`, `roleID`),
  INDEX `fk_UserXRoles_Roles_idx` (`roleID` ASC) VISIBLE,
  CONSTRAINT `fk_UserXRoles_Roles`
    FOREIGN KEY (`roleID`)
    REFERENCES `merkadit`.`mkd_Roles` (`roleID`),
  CONSTRAINT `fk_UserXRoles_Users`
    FOREIGN KEY (`userID`)
    REFERENCES `merkadit`.`mkd_Users` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
